[workspace]
resolver = "2"
members = [
    "crates/ayame-spell-core",
    "crates/ayame-spell",
    "crates/xtask",
]

[workspace.package]
version = "0.3.0"
edition = "2021"
rust-version = "1.80"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hjosugi/ayame-spell"
homepage = "https://hjosugi.github.io/ayame-spell/"
authors = ["hjosugi"]

[workspace.dependencies]
ayame-spell-core = { version = "0.3.0", path = "crates/ayame-spell-core" }

anyhow = "1"
clap = { version = "4", features = ["derive", "wrap_help"] }
clap_complete = "=4.5.58"
crossbeam-channel = "0.5"
dialoguer = "0.11"
dictgen = "0.5"
dirs = "6"
fst = { version = "0.4", features = ["levenshtein"] }
globset = "0.4"
ignore = "0.4"
lsp-server = "0.7"
lsp-types = "0.95"
memchr = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
toml = "0.8"
toml_edit = "0.22"
typos-dict = "0.13"
unicase = "2"
ureq = "2"

[profile.release]
lto = true
codegen-units = 1
strip = true
